### ISSUE TITLE
Outdated Tier List

### ISSUE THREAD

**Issue by jacob187** [desko27/smash-tier-list#10]
This appears to be about a year outdated. The main discrepancies appear to be between the S and A tiers. Additionally, I would like to see information regarding the statistics for pro smash tournaments.

**Comment by desko27** [comment]
Hi @jacob187 you're right. I'm currently not very close to the competitive scenario for Ultimate. The last time I updated this web app I relied [on this tier list](https://twitter.com/jaaahsh/status/1229812803852173313) which was built from a survey to PROs (and as you mention is currently quite outdated).

Do you know any updated/reliable source? What list would you suggest? If so please let me know, I'd be more than happy to use it. Thank you!!

**Comment by jacob187** [comment]
I don't know of any specifically, I just know the players have been adjusted since last year. There are tier lists all across Reddit and other Social Networks. In terms of Melee, I think there is an official tier list. 

Also, the search feature refreshes each time a new page loads. I think this could be adjusted using React.
